# Generated by Django 3.1.1 on 2020-09-13 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
