# Generated by Django 3.1.1 on 2020-09-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_me_text',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name_text',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
