# Generated by Django 3.1.1 on 2020-09-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20200913_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='I am a PMP student studying at UW-Madison. Add me as friend to collaborate!'),
            preserve_default=False,
        ),
    ]
