# Generated by Django 3.1.1 on 2020-09-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='t@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='hunter2', max_length=200),
            preserve_default=False,
        ),
    ]
